### ISSUE TITLE
Allow user email updates (adding additional contact email in the Profile)

### ISSUE THREAD

**Issue by sanjarogic** [PavlidisLab/rgr#22]
- [x] add a contact email in the user profile
 - [x] if set, use the contact email wherever possible for display purposes
 - [x]  gracefully fallback to the account email if the contact email is not set
 - [x] add a process for verifying the user contact email and only display verified contact emails
 - [x] show in the user profile if an email is or isn't verified
 - [x] add `email` and `verified` in the `verification_token` table to indicate which email is being verified by the token and whether the token has been successfully applied
 - [x] allow user to remove the contact email

**Comment by arteymix** [comment]
It would be a security hazard to allow the user to change its email since we use it as an account username. We need instead a contact email to be displayed in lieu of the username.

**Comment by arteymix** [comment]
The email needs to be verified to prevent potential spamming.

**Comment by arteymix** [comment]
I basically added an `email` field in the verification token so that we can tell if the token applies to the contact email or not. Also, we remove token from the database once they are used to prevent their reuse.

**Comment by arteymix** [comment]
We need a test to ensure that emptying the contact email results in a `null` value and thus the account email to be used.
